package com.bw.zhuguiquan20200106.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.zhuguiquan20200106.model.dao.LeftDao;
import com.bw.zhuguiquan20200106.model.dao.RightDao;

import com.bw.zhuguiquan20200106.database.LeftDaoDao;
import com.bw.zhuguiquan20200106.database.RightDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig leftDaoDaoConfig;
    private final DaoConfig rightDaoDaoConfig;

    private final LeftDaoDao leftDaoDao;
    private final RightDaoDao rightDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        leftDaoDaoConfig = daoConfigMap.get(LeftDaoDao.class).clone();
        leftDaoDaoConfig.initIdentityScope(type);

        rightDaoDaoConfig = daoConfigMap.get(RightDaoDao.class).clone();
        rightDaoDaoConfig.initIdentityScope(type);

        leftDaoDao = new LeftDaoDao(leftDaoDaoConfig, this);
        rightDaoDao = new RightDaoDao(rightDaoDaoConfig, this);

        registerDao(LeftDao.class, leftDaoDao);
        registerDao(RightDao.class, rightDaoDao);
    }
    
    public void clear() {
        leftDaoDaoConfig.clearIdentityScope();
        rightDaoDaoConfig.clearIdentityScope();
    }

    public LeftDaoDao getLeftDaoDao() {
        return leftDaoDao;
    }

    public RightDaoDao getRightDaoDao() {
        return rightDaoDao;
    }

}
